server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/architect?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时时间(毫秒)
      pool-name: DataSourceHikariCP # 连接池名称
      max-lifetime: 1800000 # 连接生命时长
      connection-test-query: select 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  type-aliases-package: com.study.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.study.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
